# Generated by Django 4.0.4 on 2022-04-22 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.DateTimeField(default=django.utils.timezone.now, help_text='creation date')),
                ('backup_file', models.FileField(upload_to='backup')),
            ],
        ),
    ]
