# Generated by Django 4.0.4 on 2022-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('A', 'Announce'), ('D', 'Delish'), ('L', 'Life'), ('T', 'Store'), ('S', 'Style')], default='A', help_text='Article Type', max_length=1),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.CharField(choices=[('BNK', 'Bank'), ('BUT', 'Beauty'), ('ECT', 'Electrical'), ('ENT', 'Entertainment'), ('FSH', 'Fashion'), ('FOD', 'Food'), ('FUN', 'Furniture'), ('JEW', 'Jewellery'), ('SVC', 'Services'), ('SPT', 'Sport'), ('TOY', 'Toy')], default='FOD', help_text='Store Type', max_length=3),
        ),
    ]
