# Generated by Django 4.0.4 on 2022-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_article_article_type_alter_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announce',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Image to show in list', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Image to show in list', null=True, upload_to='img'),
        ),
    ]
